// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/api/joke.ts";
import * as $3 from "./routes/fetch/handler.tsx";
import * as $4 from "./routes/fetch/route.tsx";
import * as $5 from "./routes/got/handler.tsx";
import * as $6 from "./routes/got/route.tsx";
import * as $7 from "./routes/greet/[name].tsx";
import * as $8 from "./routes/index.tsx";
import * as $$0 from "./islands/Counter.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/api/joke.ts": $2,
    "./routes/fetch/handler.tsx": $3,
    "./routes/fetch/route.tsx": $4,
    "./routes/got/handler.tsx": $5,
    "./routes/got/route.tsx": $6,
    "./routes/greet/[name].tsx": $7,
    "./routes/index.tsx": $8,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
